# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: Nzg0NzBlMDdkMDQ2OTFkZWRiM2I2YWI5MDI0OWE1NTM1ZDMwZTFkMGFiNjlkMWJkNTZjYjc4ZGYzMjM2MTYxNmE4MTk0MGE1ZWRlYWZjYTg1NGE5NTY3ZmMxMjlmZDNkMDJjYjJkODljNjRjYWMzYjQ4YmE2ZWY5ZjJlMmM3N2I=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: OperaConductor
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: system
    password: oracle
