package mc.sbm.operaconductor.service.mapper;

import java.util.Map;
import java.util.stream.Collectors;
import mc.sbm.operaconductor.GenericEvent;
import mc.sbm.operaconductor.domain.ProfileDto;
import org.springframework.stereotype.Component;

@Component
public class ProfileMapper implements SinkMapper<ProfileDto> {

    @Override
    public String eventKey() {
        return "PROFILE_NEW_PROFILE";
    }

    @Override
    public ProfileDto map(GenericEvent event) {
        return fromEvent(event);
    }

    @Override
    public Class<ProfileDto> targetClass() {
        return ProfileDto.class;
    }

    public static ProfileDto fromEvent(GenericEvent event) {
        Map<String, String> d = event
            .getDetail()
            .stream()
            .collect(
                Collectors.toMap(
                    GenericEvent.EventDetail::getElementName,
                    detail -> detail.getNewValue() != null ? detail.getNewValue() : "",
                    (existing, replacement) -> existing
                )
            );

        return ProfileDto.builder()
            // Event-level
            .timestamp(event.getTimestamp())
            .primaryKey(event.getPrimaryKey())
            .hotelId(event.getHotelId())
            // Name / identity
            .nameId(d.get("NAME ID"))
            .nameType(d.get("NAME TYPE"))
            .name(d.get("NAME"))
            .name2(d.get("NAME2"))
            .name3(d.get("NAME3"))
            .firstName(d.get("FIRST NAME"))
            .middle(d.get("MIDDLE"))
            .title(d.get("TITLE"))
            .xName(d.get("XNAME"))
            .xFirstName(d.get("XFIRST NAME"))
            .xSalutation(d.get("XSALUTATION"))
            .xTitle(d.get("XTITLE"))
            .incognitoName(d.get("INCOGNITO NAME"))
            .incognitoFirst(d.get("INCOGNITO FIRST"))
            .businessTitle(d.get("BUSINESS TITLE"))
            .language(d.get("LANGUAGE"))
            .nationality(d.get("NATIONALITY"))
            .gender(d.get("GENDER"))
            .birthDate(d.get("BIRTH DATE"))
            .birthPlace(d.get("BIRTH PLACE"))
            .birthCountry(d.get("BIRTH COUNTRY"))
            .vipStatus(d.get("VIP STATUS"))
            .status(d.get("STATUS"))
            // Address
            .address1(d.get("ADDRESS1"))
            .address2(d.get("ADDRESS2"))
            .address3(d.get("ADDRESS3"))
            .address4(d.get("ADDRESS4"))
            .city(d.get("CITY"))
            .state(d.get("STATE"))
            .postalCode(d.get("POSTAL CODE"))
            .country(d.get("COUNTRY"))
            .addressType(d.get("ADDRESS TYPE"))
            .addressPrimaryYn(d.get("ADDRESS PRIMARY YN"))
            .addressLanguage(d.get("ADDRESS LANGUAGE"))
            // Contact
            .phoneNumber(d.get("PHONE NUMBER"))
            .phonePrimaryYn(d.get("PHONE PRIMARY YN"))
            .phoneType(d.get("PHONE TYPE"))
            .phoneYn(d.get("PHONE YN"))
            .phoneOptInFlg(d.get("PHONE OPT IN FLG"))
            .faxNumber(d.get("FAX NUMBER"))
            .pager(d.get("PAGER"))
            .virtualNumber(d.get("VIRTUAL NUMBER"))
            .email(d.get("EMAIL"))
            .emailLanguage(d.get("EMAIL LANGUAGE"))
            .emailYn(d.get("EMAIL YN"))
            .emailOptInFlg(d.get("EMAIL OPT IN FLG"))
            .webpage(d.get("WEBPAGE"))
            // Identifications
            .idNumber(d.get("ID NUMBER"))
            .idType(d.get("ID TYPE"))
            .idDate(d.get("ID DATE"))
            .idExpirationDate(d.get("ID EXPIRATION DATE"))
            .idPlace(d.get("ID PLACE"))
            .idCountry(d.get("ID COUNTRY"))
            .passportNumber(d.get("PASSPORT NUMBER"))
            // Tax / legal
            .taxNumber1(d.get("TAX NUMBER1"))
            .taxNumber2(d.get("TAX NUMBER2"))
            .legalCompany(d.get("LEGAL COMPANY"))
            // Company / industry
            .companyNumber(d.get("COMPANY NUMBER"))
            .companyType(d.get("COMPANY TYPE"))
            .industryCode(d.get("INDUSTRY CODE"))
            .iataNumber(d.get("IATA NUMBER"))
            .iataType(d.get("IATA TYPE"))
            .chainCode(d.get("CHAIN CODE"))
            .databaseId(d.get("DATABASE ID"))
            // Membership
            .membershipNumber(d.get("MEMBERSHIP NUMBER"))
            .membershipType(d.get("MEMBERSHIP TYPE"))
            .membershipLevel(d.get("MEMBERSHIP LEVEL"))
            .membershipExpirationDate(d.get("MEMBERSHIP EXPIRATION DATE"))
            .membershipEnrolledAt(d.get("MEMBERSHIP ENROLLED AT"))
            .membershipEnrollmentSource(d.get("MEMBERSHIP ENROLLMENT SOURCE"))
            .membershipDeviceCode(d.get("MEMBERSHIP DEVICE CODE"))
            .membershipDeviceDisableDate(d.get("MEMBERSHIP DEVICE DISABLE DATE"))
            .autoEnrollMembershipYn(d.get("AUTO ENROLL MEMBERSHIP YN"))
            .autoEnrollMembershipOptInFlg(d.get("AUTO ENROLL MEMBERSHIP OPT IN FLG"))
            // Preferences
            .preferenceGroup(d.get("PREFERENCE GROUP"))
            .preferenceType(d.get("PREFERENCE TYPE"))
            .preferenceTypeDescription(d.get("PREFERENCE TYPE DESCRIPTION"))
            // Keywords
            .keyword(d.get("KEYWORD"))
            .keywordType(d.get("KEYWORD TYPE"))
            // A/R & financial
            .arNumber(d.get("A/R NUMBER"))
            .centralArNumber(d.get("CENTRAL AR NUMBER"))
            .creditRating(d.get("CREDIT RATING"))
            .cashBlInd(d.get("CASH BL IND"))
            .blMsg(d.get("BL MSG"))
            .adjustmentAmount(d.get("ADJUSTMENT AMOUNT"))
            .adjustmentCode(d.get("ADJUSTMENT CODE"))
            .adjustmentType(d.get("ADJUSTMENT TYPE"))
            .commissionCode(d.get("COMMISSION CODE"))
            .commissionCurrency(d.get("COMMISSION CURRENCY"))
            .accountSource(d.get("ACCOUNT SOURCE"))
            .accountType(d.get("ACCOUNT TYPE"))
            // Credit card
            .creditCardNumber(d.get("CREDIT CARD NUMBER"))
            .creditCardNumber4Digits(d.get("CREDIT CARD NUMBER 4 DIGITS"))
            .creditCardExpirationDate(d.get("CREDIT CARD EXPIRATION DATE"))
            .creditCardType(d.get("CREDIT CARD TYPE"))
            .creditCardVaultId(d.get("CREDIT CARD VAULT ID"))
            // Access / rate
            .accessChannel(d.get("ACCESS CHANNEL"))
            .accessChannelCode(d.get("ACCESS CHANNEL CODE"))
            .accessCode(d.get("ACCESS CODE"))
            .accessRateCode(d.get("ACCESS RATE CODE"))
            .accessResorts(d.get("ACCESS RESORTS"))
            .accessInactiveDate(d.get("ACCESS INACTIVE DATE"))
            .accessUpdateDate(d.get("ACCESS UPDATE DATE"))
            .rateCode(d.get("RATE CODE"))
            // PCC
            .pccChannel(d.get("PCC CHANNEL"))
            .pccCode(d.get("PCC CODE"))
            .pccInactiveDate(d.get("PCC INACTIVE DATE"))
            // Sales / marketing
            .salesManager(d.get("SALES MANAGER"))
            .markets(d.get("MARKETS"))
            .scope(d.get("SCOPE"))
            .scopeCity(d.get("SCOPE CITY"))
            .influence(d.get("INFLUENCE"))
            .priority(d.get("PRIORITY"))
            .profession(d.get("PROFESSION"))
            .roomsPotential(d.get("ROOMS POTENTIAL"))
            .competitionCode(d.get("COMPETITION CODE"))
            .notification(d.get("NOTIFICATION"))
            // Opt-ins
            .mailingListYn(d.get("MAILING LIST YN"))
            .mailingListOptInFlg(d.get("MAILING LIST OPT IN FLG"))
            .marketResearchYn(d.get("MARKET RESEARCH YN"))
            .marketResearchOptInFlg(d.get("MARKET RESEARCH OPT IN FLG"))
            .thirdPartyYn(d.get("THIRD PARTY YN"))
            .thirdPartyOptInFlg(d.get("THIRD PARTY OPT IN FLG"))
            .smsYn(d.get("SMS YN"))
            .smsOptInFlg(d.get("SMS OPT IN FLG"))
            .guestPrivacyYn(d.get("GUEST PRIVACY YN"))
            .guestPrivacyOptInFlg(d.get("GUEST PRIVACY OPT IN FLG"))
            .contactYn(d.get("CONTACT YN"))
            // Misc
            .actionCode(d.get("ACTION CODE"))
            .barcode(d.get("BARCODE"))
            .createdBy(d.get("CREATED BY"))
            .anonymizationDate(d.get("ANONYMIZATION DATE"))
            .anonymizationStatus(d.get("ANONYMIZATION STATUS"))
            .comments(d.get("COMMENTS"))
            .departmentNoteShort(d.get("DEPARTMENT NOTE SHORT"))
            .resortLogged(d.get("RESORT LOGGED"))
            .resortRegistered(d.get("RESORT REGISTERED"))
            // UDF Char (01-40)
            .udfChar01(d.get("UDF CHAR 01"))
            .udfChar02(d.get("UDF CHAR 02"))
            .udfChar03(d.get("UDF CHAR 03"))
            .udfChar04(d.get("UDF CHAR 04"))
            .udfChar05(d.get("UDF CHAR 05"))
            .udfChar06(d.get("UDF CHAR 06"))
            .udfChar07(d.get("UDF CHAR 07"))
            .udfChar08(d.get("UDF CHAR 08"))
            .udfChar09(d.get("UDF CHAR 09"))
            .udfChar10(d.get("UDF CHAR 10"))
            .udfChar11(d.get("UDF CHAR 11"))
            .udfChar12(d.get("UDF CHAR 12"))
            .udfChar13(d.get("UDF CHAR 13"))
            .udfChar14(d.get("UDF CHAR 14"))
            .udfChar15(d.get("UDF CHAR 15"))
            .udfChar16(d.get("UDF CHAR 16"))
            .udfChar17(d.get("UDF CHAR 17"))
            .udfChar18(d.get("UDF CHAR 18"))
            .udfChar19(d.get("UDF CHAR 19"))
            .udfChar20(d.get("UDF CHAR 20"))
            .udfChar21(d.get("UDF CHAR 21"))
            .udfChar22(d.get("UDF CHAR 22"))
            .udfChar23(d.get("UDF CHAR 23"))
            .udfChar24(d.get("UDF CHAR 24"))
            .udfChar25(d.get("UDF CHAR 25"))
            .udfChar26(d.get("UDF CHAR 26"))
            .udfChar27(d.get("UDF CHAR 27"))
            .udfChar28(d.get("UDF CHAR 28"))
            .udfChar29(d.get("UDF CHAR 29"))
            .udfChar30(d.get("UDF CHAR 30"))
            .udfChar31(d.get("UDF CHAR 31"))
            .udfChar32(d.get("UDF CHAR 32"))
            .udfChar33(d.get("UDF CHAR 33"))
            .udfChar34(d.get("UDF CHAR 34"))
            .udfChar35(d.get("UDF CHAR 35"))
            .udfChar36(d.get("UDF CHAR 36"))
            .udfChar37(d.get("UDF CHAR 37"))
            .udfChar38(d.get("UDF CHAR 38"))
            .udfChar39(d.get("UDF CHAR 39"))
            .udfChar40(d.get("UDF CHAR 40"))
            // UDF Number (01-40)
            .udfNumber01(d.get("UDF NUMBER 01"))
            .udfNumber02(d.get("UDF NUMBER 02"))
            .udfNumber03(d.get("UDF NUMBER 03"))
            .udfNumber04(d.get("UDF NUMBER 04"))
            .udfNumber05(d.get("UDF NUMBER 05"))
            .udfNumber06(d.get("UDF NUMBER 06"))
            .udfNumber07(d.get("UDF NUMBER 07"))
            .udfNumber08(d.get("UDF NUMBER 08"))
            .udfNumber09(d.get("UDF NUMBER 09"))
            .udfNumber10(d.get("UDF NUMBER 10"))
            .udfNumber11(d.get("UDF NUMBER 11"))
            .udfNumber12(d.get("UDF NUMBER 12"))
            .udfNumber13(d.get("UDF NUMBER 13"))
            .udfNumber14(d.get("UDF NUMBER 14"))
            .udfNumber15(d.get("UDF NUMBER 15"))
            .udfNumber16(d.get("UDF NUMBER 16"))
            .udfNumber17(d.get("UDF NUMBER 17"))
            .udfNumber18(d.get("UDF NUMBER 18"))
            .udfNumber19(d.get("UDF NUMBER 19"))
            .udfNumber20(d.get("UDF NUMBER 20"))
            .udfNumber21(d.get("UDF NUMBER 21"))
            .udfNumber22(d.get("UDF NUMBER 22"))
            .udfNumber23(d.get("UDF NUMBER 23"))
            .udfNumber24(d.get("UDF NUMBER 24"))
            .udfNumber25(d.get("UDF NUMBER 25"))
            .udfNumber26(d.get("UDF NUMBER 26"))
            .udfNumber27(d.get("UDF NUMBER 27"))
            .udfNumber28(d.get("UDF NUMBER 28"))
            .udfNumber29(d.get("UDF NUMBER 29"))
            .udfNumber30(d.get("UDF NUMBER 30"))
            .udfNumber31(d.get("UDF NUMBER 31"))
            .udfNumber32(d.get("UDF NUMBER 32"))
            .udfNumber33(d.get("UDF NUMBER 33"))
            .udfNumber34(d.get("UDF NUMBER 34"))
            .udfNumber35(d.get("UDF NUMBER 35"))
            .udfNumber36(d.get("UDF NUMBER 36"))
            .udfNumber37(d.get("UDF NUMBER 37"))
            .udfNumber38(d.get("UDF NUMBER 38"))
            .udfNumber39(d.get("UDF NUMBER 39"))
            .udfNumber40(d.get("UDF NUMBER 40"))
            // UDF Date (01-20)
            .udfDate01(d.get("UDF DATE 01"))
            .udfDate02(d.get("UDF DATE 02"))
            .udfDate03(d.get("UDF DATE 03"))
            .udfDate04(d.get("UDF DATE 04"))
            .udfDate05(d.get("UDF DATE 05"))
            .udfDate06(d.get("UDF DATE 06"))
            .udfDate07(d.get("UDF DATE 07"))
            .udfDate08(d.get("UDF DATE 08"))
            .udfDate09(d.get("UDF DATE 09"))
            .udfDate10(d.get("UDF DATE 10"))
            .udfDate11(d.get("UDF DATE 11"))
            .udfDate12(d.get("UDF DATE 12"))
            .udfDate13(d.get("UDF DATE 13"))
            .udfDate14(d.get("UDF DATE 14"))
            .udfDate15(d.get("UDF DATE 15"))
            .udfDate16(d.get("UDF DATE 16"))
            .udfDate17(d.get("UDF DATE 17"))
            .udfDate18(d.get("UDF DATE 18"))
            .udfDate19(d.get("UDF DATE 19"))
            .udfDate20(d.get("UDF DATE 20"))
            .build();
    }
}
